ARKernel:
  AUSLAN: 0.918
  ArabicDigits: 0.988
  CMUsubject16: 1.0
  CharacterTrajectories: 0.9
  DigitShapes: 1.0
  ECG: 0.82
  JapaneseVowels: 0.984
  KickvsPunch: 0.927
  LIBRAS: 0.952
  NetFlow: .nan
  PEMS: 0.75
  PenDigits: 0.952
  Shapes: 1.0
  UWave: 0.904
  Wafer: 0.968
  WalkvsRun: 1.0
DTW:
  AUSLAN: 0.727
  ArabicDigits: 0.908
  CMUsubject16: 0.93
  CharacterTrajectories: 0.948
  DigitShapes: 1.0
  ECG: 0.79
  JapaneseVowels: 0.962
  KickvsPunch: 0.6
  LIBRAS: 0.888
  NetFlow: 0.976
  PEMS: 0.832
  PenDigits: 0.927
  Shapes: 1.0
  UWave: 0.916
  Wafer: 0.974
  WalkvsRun: 1.0
LPS:
  AUSLAN: 0.754
  ArabicDigits: 0.971
  CMUsubject16: 1.0
  CharacterTrajectories: 0.965
  DigitShapes: 1.0
  ECG: 0.82
  JapaneseVowels: 0.951
  KickvsPunch: 0.9
  LIBRAS: 0.903
  NetFlow: 0.968
  PEMS: 0.844
  PenDigits: 0.908
  Shapes: 1.0
  UWave: 0.98
  Wafer: 0.962
  WalkvsRun: 1.0
SMTS:
  AUSLAN: 0.947
  ArabicDigits: 0.964
  CMUsubject16: 0.997
  CharacterTrajectories: 0.992
  DigitShapes: 1.0
  ECG: 0.818
  JapaneseVowels: 0.969
  KickvsPunch: 0.82
  LIBRAS: 0.909
  NetFlow: 0.977
  PEMS: 0.896
  PenDigits: 0.917
  Shapes: 1.0
  UWave: 0.941
  Wafer: 0.965
  WalkvsRun: 1.0
gRSF:
  AUSLAN: 0.955
  ArabicDigits: 0.975
  CMUsubject16: 1.0
  CharacterTrajectories: 0.994
  DigitShapes: 1.0
  ECG: 0.88
  JapaneseVowels: 0.8
  KickvsPunch: 1.0
  LIBRAS: 0.911
  NetFlow: 0.914
  PEMS: 1.0
  PenDigits: 0.932
  Shapes: 1.0
  UWave: 0.929
  Wafer: 0.992
  WalkvsRun: 1.0
mvARF:
  AUSLAN: 0.934
  ArabicDigits: 0.952
  CMUsubject16: 1.0
  CharacterTrajectories: 0.928
  DigitShapes: 1.0
  ECG: 0.785
  JapaneseVowels: 0.959
  KickvsPunch: 0.976
  LIBRAS: 0.945
  NetFlow: .nan
  PEMS: .nan
  PenDigits: 0.923
  Shapes: 1.0
  UWave: 0.952
  Wafer: 0.931
  WalkvsRun: 1.0
MUSE:
  AUSLAN: 0.97
  ArabicDigits: 0.992
  CMUsubject16: 1.0
  CharacterTrajectories: 0.937
  DigitShapes: 1.0
  ECG: 0.88
  JapaneseVowels: 0.976
  KickvsPunch: 1.0
  LIBRAS: 0.894
  NetFlow: 0.961
  PEMS: .nan
  PenDigits: 0.912
  Shapes: 1.0
  UWave: 0.916
  Wafer: 0.997
  WalkvsRun: 1.0
MLSTMFCN:
  AUSLAN: 0.95
  ArabicDigits: 0.99
  CMUsubject16: 1.0
  CharacterTrajectories: 0.99
  DigitShapes: 1.0
  ECG: 0.87
  JapaneseVowels: 1.0
  KickvsPunch: 0.9
  LIBRAS: 0.97
  NetFlow: 0.95
  PEMS: .nan
  PenDigits: 0.97
  Shapes: 1.0
  UWave: 0.97
  Wafer: 0.99
  WalkvsRun: 1.0